services:

### RabbitMQ ###
  rabbitmq:
    image: rabbitmq:3-management
    container_name: order-management-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservice-network

### Order Management - PostgreSQL ###
  order-management-postgres:
    container_name: order-management-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_management
    networks:
      - microservice-network
    volumes:
      - order-management-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

### Order Management - Application ###
  order-management:
    container_name: order-management-app-container
    image: order-management-app-image
    build:
      context: ./order-management-microservice
      dockerfile: Dockerfile
    restart: always
    depends_on:
      order-management-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-management-postgres:5432/order_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - microservice-network

### Delivery Logistic - PostgreSQL ###
  delivery-logistic-postgres:
    container_name: delivery-logistic-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery_logistic
    networks:
      - microservice-network
    volumes:
      - delivery-logistic-data:/var/lib/postgresql/data  # Separate volume for this DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

### Delivery Logistic - Application ###
  delivery-logistic:
    container_name: delivery-logistic-app-container
    image: delivery-logistic-app-image
    build:
      context: ./delivery-logistic-microservice
      dockerfile: Dockerfile
    restart: always
    depends_on:
      delivery-logistic-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://delivery-logistic-postgres:5432/delivery_logistic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - microservice-network

### Product Catalog - PostgreSQL ###
  product-catalog-postgres:
    container_name: product-catalog-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_catalog
    networks:
      - microservice-network
    volumes:
      - product-catalog-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

### Product Catalog - Application ###
  product-catalog:
    container_name: product-catalog-app-container
    image: product-catalog-app-image
    build:
      context: ./product_catalog_microservice
      dockerfile: Dockerfile
    restart: always
    depends_on:
      product-catalog-postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-catalog-postgres:5432/product_catalog
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - microservice-network

### Client - PostgreSQL ###
  client-postgres:
    container_name: client-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: client
    networks:
      - microservice-network
    volumes:
      - client-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

### Client  - Application ###
  client-microservice:
    container_name: client-app-container
    image: client-app-image
    build:
      context: ./client_microservice
      dockerfile: Dockerfile
    restart: always
    depends_on:
      client-postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://client-postgres:5432/client
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - microservice-network

### API Gateway ###
  api-gateway:
    container_name: api-gateway
    image: api-gateway-image
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - order-management
      - delivery-logistic
      - product-catalog
      - client-microservice
    ports:
      - "8081:8081"
    networks:
      - microservice-network

### Volumes ###
volumes:
  order-management-data:
  delivery-logistic-data:
  product-catalog-data:
  client-data:

### Network ###
networks:
  microservice-network:
    driver: bridge
