
### POST
POST http://localhost:8080/api/orders
Content-Type: application/json

{
    "customerId": "d2f7a49a-4c2b-4c70-8c21-22a7c0199d3b",
    "creationDate": "2025-01-27T10:00:00Z",
    "total": 99.99,
    "orderProducts": [
        {
            "productId": "a3c5b788-0f3c-4c50-bbe3-3bbd0c3f6d72",
            "quantity": 2,
            "unitPrice": 49.99
        }
    ]
}

### GET
GET http://localhost:8082/api/deliveries


### GET
GET http://localhost:8080/api/orders
Content-Type: application/json

### GET by ID
GET http://localhost:8080/api/orders/4dadcee0-a879-4790-b6c9-417963b51c6e
Content-Type: application/json

### PUT
PUT http://localhost:8080/api/orders/4dadcee0-a879-4790-b6c9-417963b51c6e
Content-Type: application/json

{
  "status": "PROCESSING"
}

### DELETE
DELETE http://localhost:8080/api/orders
Content-Type: application/json