# Server Configuration
server:
  port: 9000

# API Name
spring:
  application:
    name: order-management-microservice
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        orderCreated-out-0:
          destination: orders.exchange
          content-type: application/json
        orderDeleted-out-0:
          destination: orders.delete.exchange
          content-type: application/json

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/order_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
