server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - AddResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE, OPTIONS
        - AddResponseHeader=Access-Control-Allow-Headers, Origin, Content-Type, Accept, Authorization
        - AddResponseHeader=Access-Control-Allow-Credentials, true
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST
      
      routes:
        
        - id: order-management-service
          uri: http://order-management:9000
          predicates:
            - Path=/api/orders/**

        # Swagger Ordem
        - id: order-management-swagger
          uri: http://order-management:9000
          predicates:
            - Path=/swagger/pedido/v3/api-docs
          filters:
            - SetPath=/api-docs

        - id: delivery-management-service
          uri: http://delivery-logistic:10000
          predicates:
            - Path=/api/deliveries/**

        # Swagger Delivery
        - id: delivery-management-swagger
          uri: http://delivery-logistic:10000
          predicates:
            - Path=/swagger/delivery/v3/api-docs
          filters:
            - SetPath=/api-docs

        - id: product-catalog-service
          uri: http://product-catalog:11000
          predicates:
            - Path=/api/produtos/**

        # Swagger Produto
        - id: product-catalog-swagger
          uri: http://product-catalog:11000
          predicates:
            - Path=/swagger/produto/v3/api-docs
          filters:
            - SetPath=/api-docs

        - id: client-service
          uri: http://client-microservice:12000
          predicates:
            - Path=/api/clientes/**

        # Swagger Cliente
        - id: client-service-swagger
          uri: http://client-microservice:12000
          predicates:
            - Path=/swagger/clientes/v3/api-docs
          filters:
            - SetPath=/api-docs

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
    #disable-swagger-default-url: true
    enabled: true
    urls:
      - name: pedido
        url: /swagger/pedido/v3/api-docs
      - name: delivery
        url: /swagger/delivery/v3/api-docs
      - name: produto
        url: /swagger/produto/v3/api-docs
      - name: clientes
        url: /swagger/clientes/v3/api-docs


