# Server Configuration
server:
  port: 8085

# API Name
spring:
  application:
    name: client_microservice

  # Database Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/client
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
