services:
  delivery-management-db-postgres:
    container_name: delivery-management-db
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery_logistic
    networks:
      - order-management-network
    volumes:
      - delivery-logistic-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  delivery-logistic-data:

networks:
  order-management-network:
