
### POST
POST http://localhost:8080/api/orders
Content-Type: application/json

{
    "customerId": "d2f7a49a-4c2b-4c70-8c21-22a7c0199d3b",
    "creationDate": "2025-01-27T10:00:00Z",
    "total": 99.99,
    "orderProducts": [
        {
            "productId": "a3c5b788-0f3c-4c50-bbe3-3bbd0c3f6d72",
            "quantity": 2,
            "unitPrice": 49.99
        }
    ]
}


### POST
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "orderId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "customerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "status": "CREATED",
  "creationDate": "2025-02-16T20:39:53.087Z",
  "total": 0,
  "orderProducts": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "productId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "quantity": 0,
      "unitPrice": 0
    }
  ]
}

### GET
GET http://localhost:8081/api/deliveries


### GET
GET http://localhost:8080/api/orders
Content-Type: application/json

### GET by ID
GET http://localhost:8081/api/orders/4dadcee0-a879-4790-b6c9-417963b51c6e
Content-Type: application/json

### PUT
PUT http://localhost:8081/api/orders/4dadcee0-a879-4790-b6c9-417963b51c6e
Content-Type: application/json

{
  "status": "PROCESSING"
}

### DELETE
DELETE http://localhost:8081/api/orders
Content-Type: application/json